server:
  port: 9090

spring:
  datasource:
    repository: com.example.demo.repository
    #url: jdbc:oracle:thin:@10.1.1.39:1521:cloud
    #username: cloud
    #password: cloud
    #driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:mysql://10.1.1.175:3306/cloud3?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml